name: Build
on:
  workflow_dispatch:
  push:
    tags: ["v*"]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.12"}
      - run: pipx install poetry
      - run: poetry install --with build
      - run: poetry run pyinstaller --clean --noconfirm pixopdf.spec
      - uses: actions/upload-artifact@v4
        with:
          name: PixoPDF-${{ runner.os }}
          path: dist/
